import { SampleCar } from '../types/vehicle';

export const SAMPLE_CARS: SampleCar[] = [
  {
    id: 'hyundai-creta-white',
    title: 'Hyundai Creta',
    make: 'Hyundai',
    model: 'Creta',
    colour: 'White',
    colorHex: '#F8F9FA',
    tag: 'Compact SUV (Prompt Spec)',
    imageUrl: 'https://images.unsplash.com/photo-1549399542-7e3f8b79c341?auto=format&fit=crop&w=1000&q=80',
    description: 'Popular compact SUV featuring parametric jewel front grille and Polar White paint finish.',
  },
  {
    id: 'bmw-3series-black',
    title: 'BMW 3 Series',
    make: 'BMW',
    model: '3 Series',
    colour: 'Black',
    colorHex: '#18191A',
    tag: 'Executive Sedan (Prompt Spec)',
    imageUrl: 'https://images.unsplash.com/photo-1555215695-3004980ad54e?auto=format&fit=crop&w=1000&q=80',
    description: 'Sporty luxury executive sedan finished in Black Sapphire Metallic paint with signature kidney grille.',
  },
  {
    id: 'toyota-white-suv',
    title: 'Toyota Innova / Fortuner',
    make: 'Toyota',
    model: 'Innova Crysta',
    colour: 'White',
    colorHex: '#EEEEEE',
    tag: 'Multi-Purpose Vehicle',
    imageUrl: 'https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?auto=format&fit=crop&w=1000&q=80',
    description: 'Robust family SUV / MPV known for reliability, spacious cabin, and Super White exterior.',
  },
  {
    id: 'red-sports-car',
    title: 'Porsche 911 Carrera',
    make: 'Porsche',
    model: '911 Carrera',
    colour: 'Red',
    colorHex: '#D71921',
    tag: 'Sports Car',
    imageUrl: 'https://images.unsplash.com/photo-1614162692292-7ac56d7f7f1e?auto=format&fit=crop&w=1000&q=80',
    description: 'High-performance rear-engine sports car in iconic Guards Red with sleek aerodynamic contours.',
  },
  {
    id: 'multi-cars-street',
    title: 'Multiple Cars (Street Traffic)',
    make: 'Various',
    model: 'Multi-Vehicle Detection',
    colour: 'Multi-colour',
    colorHex: '#3B82F6',
    tag: 'Multi-Car Test Case',
    imageUrl: 'https://images.unsplash.com/photo-1502877338535-766e1452684a?auto=format&fit=crop&w=1000&q=80',
    description: 'Street scene with multiple vehicles to test bounding boxes and multi-car interactive selection.',
    isMultiCar: true,
  },
];
